import Navbar from '@/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Api-Usuarios',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className=" bg-slate-900  container mx-auto h-[calc(100vh-4rem)] mt-14 flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
